bgh/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('hvac/', include('hvac.urls')),
]

hvac/urls.py
from django.urls import path

from . import views

# added for namespace isolation
app_name = 'hvac'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:hvac_id>/command/', views.command, name='command'),
    path('<int:hvac_id>/plot/', views.plot, name='plot'),
]

hvac/models.py
from django.db import models


class Hvac(models.Model):
    """HVAC model, to handle all home devices"""
    equipment = models.CharField(max_length=200)
    description = models.CharField(max_length=200)

    def __str__(self):
        return self.description


class Command(models.Model):
    """Command model, traceability of commands issued"""

    hvac = models.ForeignKey(Hvac, on_delete=models.CASCADE)
    hvac_webid = models.CharField(max_length=200)
    room_temperature = models.FloatField()
    target_temperature = models.FloatField()
    fan_speed = models.CharField(max_length=10)
    mode = models.CharField(max_length=10)
    date_issued = models.DateTimeField('date issued')

    def __str__(self):
        return "%s - %s" % (self.date_issued, self.mode)

hvac/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.template import loader
from django.shortcuts import render, get_object_or_404, reverse
from django.http import Http404
from django.views import generic
from django.utils import timezone
from .models import Hvac, Command
from django.conf import settings
import requests


class IndexView(generic.ListView):
    """Index view, , no special treatment, all HVAC's are shown"""
    template_name = 'hvac/index.html'
    context_object_name = 'list_hvacs'
    model = Hvac


class DetailView(generic.DetailView):
    """Detail view"""
    model = Hvac
    template_name = 'hvac/detail.html'


def command(request, hvac_id):
    """Receive the new HVAC parameters and apply them"""
    hvac = get_object_or_404(Hvac, pk=hvac_id)

    cmd = Command.objects.create(room_temperature=10, target_temperature=request.POST['temp'],
                                 date_issued=timezone.now(), fan_speed=request.POST['fan'], mode=request.POST['mode'],
                                 hvac_webid=hvac.equipment, hvac=hvac
                                 )
    a = BghClient(settings.HVAC_USER, settings.HVAC_PASSWD)
    a.set_mode(hvac.equipment, request.POST['mode'], request.POST['temp'])

    return HttpResponseRedirect(reverse('hvac:index', args=()))


def plot(request, hvac_id):
    """Return a Json object with the history of user targeted temps for the corresponding HVAC"""
    commands = Command.objects.filter(hvac=hvac_id)
    temperatures = []
    for cmd in commands:
        temperatures.append(cmd.target_temperature)
    return JsonResponse({'temperature_data_set': temperatures})


class BghClient():
    """Class to handle the interactions to the HVAC controller endpoint."""

    def __init__(self, email, password):
        self.token = self._login(email, password)

    @staticmethod
    def _login(email, password):
        endpoint = "%s/control/LoginPage.aspx/DoStandardLogin" % settings._BASE_URL
        resp = requests.post(endpoint, json={'user': email, 'password': password})
        return resp.json()['d']

    def _request(self, endpoint, payload=None):
        """Request function will always enforce the auth Tokens."""
        if payload is None:
            payload = {}
        payload['token'] = {'Token': self.token}
        return requests.post(endpoint, json=payload)

    def _get_data_packets(self, home_id):
        """Get data packets as the api calls them."""
        endpoint = "%s/HomeCloudService.svc/GetDataPacket" % settings._API_URL
        payload = {
            'homeID': home_id,
            'serials': {
                'Home': 0,
                'Groups': 0,
                'Devices': 0,
                'Endpoints': 0,
                'EndpointValues': 0,
                'Scenes': 0,
                'Macros': 0,
                'Alarms': 0
            },
            'timeOut': 10000
        }
        resp = self._request(endpoint, payload)
        return resp.json()['GetDataPacketResult']

    def get_homes(self):
        """Get all the homes of the account"""
        endpoint = "%s/HomeCloudService.svc/EnumHomes" % settings._API_URL
        resp = self._request(endpoint)
        return resp.json()['EnumHomesResult']['Homes']

    def get_devices(self, home_id):
        """Get all the devices of a home"""
        data = self._get_data_packets(home_id)
        return data

    def get_HVAC_status(self, endpoint):
        """Get the current status of the HVAC's @ home
            (room_temperature, target_temperature, fan_speed, mode)
        """
        status = {}
        devices = self.get_devices(settings.HVAC_HOMEID)
        for device in devices['EndpointValues']:
            if device['EndpointID'] == endpoint:
                status = self._parse_values(device['Values'])
        return status

    def _set_device_mode(self, device_id, mode):
        """Issue the command to the HVAC endpoint"""
        mode['endpointID'] = device_id
        endpoint = "%s/HomeCloudCommandService.svc/HVACSetModes" % settings._API_URL
        resp = self._request(endpoint, mode)
        return resp

    def set_mode(self, device_id, mode, temp, fan='auto'):
        """Set the mode of a device"""
        config = {
            'desiredTempC': str(temp),
            'fanMode': settings.FAN_MODE[fan],
            'flags': 255,
            'mode': settings.MODE[mode]
        }
        return self._set_device_mode(device_id, config)

    def _parse_values(self, values):
        """Parse values for each device
        Will try to decode MODE and FAN SPEED
        TODO: Show this values in the app."""

        parsed_vals = {}
        # ValueTypes of our interest
        conv_dict = {13: 'RoomTemp', 20: 'TargetTemp', 15: 'FanSpeed', 14: 'HvacMode'}

        for value in values:
            if value['ValueType'] in conv_dict.keys():
                parsed_vals[conv_dict[int(value['ValueType'])]] = value['Value']
        try:
            parsed_vals['HvacMode'] = \
                settings.MODE.keys()[settings.MODE.values().index(int(parsed_vals['HvacMode']))]

            parsed_vals['FanSpeed'] = \
                settings.FAN_MODE.keys()[settings.FAN_MODE.values().index(int(parsed_vals['FanSpeed']))]
        except:
            pass

        return parsed_vals

hvac/templates/hvac/detail.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <title>MyHVAC's command</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
            integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
            crossorigin="anonymous"></script>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/starter-template/">

    <link href="../assets/dist/css/bootstrap.css" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

    </style>
    <!-- Custom styles for this template -->
    <link href="starter-template.css" rel="stylesheet">
</head>
<body>
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="../">MyHvac's</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
            aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true"
                   aria-expanded="false">Admin</a>
                <div class="dropdown-menu" aria-labelledby="dropdown01">
                    <a class="dropdown-item" href="../../admin/hvac">Admin</a>
                    <a class="dropdown-item" href="../../admin/hvac/hvac">Hvac Config</a>
                    <a class="dropdown-item" href="../../admin/hvac/command">Command History</a>
                </div>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>

<main role="main" class="container">

    <div class="starter-template">
        <h1>Bootstrap starter template</h1>
        <p class="lead"></p>
    </div>

</main><!-- /.container -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="../assets/js/vendor/jquery.slim.min.js"><\/script>')</script>
<script src="../assets/dist/js/bootstrap.bundle.js"></script>
</body>

<h1>{{ hvac.description }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'hvac:command' hvac.id %}" method="post">
    {% csrf_token %}

    <div class="form-group">
        <label for="temp">Target Temperature</label>
        <input type="number" placeholder="24" class="form-control" name="temp" id="temp" value="24">
        <small id="tempHelp" class="form-text text-muted">This is the new target temperature for your HVAC.</small>
    </div>
    <div class="form-group">
        <label for="fan">Fan Speed</label>
        <select class="form-control" id="fan" name="fan">
            <option value="slow">Slow</option>
            <option value="mid">Mid</option>
            <option value="high">High</option>
            <option value="auto">Auto</option>
        </select>
        <small id="fanHelp" class="form-text text-muted">Please select desired fan speed.</small>
    </div>

    <div class="form-group">
        <label for="fan">HVAC Mode</label>
        <select class="form-control" id="mode" name="mode">
            <option value="off">Off</option>
            <option value="cool">Cool</option>
            <option value="heat">Heat</option>
            <option value="dry">Dry</option>
            <option value="fan">Fan</option>
            <option value="auto">Auto</option>
        </select>
        <small id="fanHelp" class="form-text text-muted">Please select desired HVAC mode.</small>
    </div>

    <button type="submit" class="btn btn-primary">Send Command</button>
</form>


<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/export-data.js"></script>
<script src="https://code.highcharts.com/modules/accessibility.js"></script>

<script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="
        crossorigin="anonymous"></script>

<figure class="highcharts-figure">
    <div id="container" style="height: 300px; width: 500px"></div>
</figure>

<script type="text/javascript">

    var myTempChart = Highcharts.chart('container', {
    chart: {
        type: 'area'
    },
    title: {
        text: 'Avg. of target temps issued'
    },
    yAxis: {
        title: {
            text: 'Target Temperature (°C)'
        }
    },
    plotOptions: {
        line: {
            dataLabels: {
                enabled: true
            },
            enableMouseTracking: false
        }
    },
    series: [{
        name: 'Temperature set',
        data: []
    }]
});

    $.getJSON('http://localhost:8000/hvac/{{ hvac.id }}/plot/',
        function (data) {
            var series = myTempChart.series[0];
            series.setData(data.temperature_data_set);
        }
    );

</script>

</html>

hvac/templates/hvac/index.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <title>MyHVAC's list</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
            integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
            crossorigin="anonymous"></script>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/starter-template/">

    <link href="../assets/dist/css/bootstrap.css" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

    </style>
    <!-- Custom styles for this template -->
    <link href="starter-template.css" rel="stylesheet">
</head>
<body>
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="#">MyHvac's</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
            aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true"
                   aria-expanded="false">Admin</a>
                <div class="dropdown-menu" aria-labelledby="dropdown01">
                    <a class="dropdown-item" href="../admin/hvac">Admin</a>
                    <a class="dropdown-item" href="../admin/hvac/hvac">Hvac Config</a>
                    <a class="dropdown-item" href="../admin/hvac/command">Command History</a>
                </div>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>

<main role="main" class="container">
    <div class="starter-template">
        <h1>Bootstrap starter template</h1>
        <p class="lead"></p>
    </div>

</main><!-- /.container -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="../assets/js/vendor/jquery.slim.min.js"><\/script>')</script>
<script src="../assets/dist/js/bootstrap.bundle.js"></script>
</body>

{% load static %}
{% if list_hvacs %}
<ul class="list-group">
    {% for hvac in list_hvacs %}
    <li class="list-group-item list-group-item-action"><a href="{% url 'hvac:detail' hvac.id %}">{{ hvac.description }}</a></li>
    {% endfor %}
</ul>
{% else %}
<p>No hvacs are available.</p>
{% endif %}

</html>